ALTER SESSION SET CURRENT_SCHEMA = pobyrne;

-- 1.
SELECT Coder_Name, COUNT(CD_ATTENDS.Coder_Id) sessions_attended
FROM CD_ATTENDEE
JOIN CD_ATTENDS ON CD_ATTENDS.Coder_Id = CD_ATTENDEE.Coder_Id
GROUP BY Coder_Name
HAVING COUNT(CD_ATTENDS.Coder_Id) > 1;

-- 2.
SELECT Organizer_Name, CD_LOCATION.loc_name
FROM CD_ORGANIZER
JOIN CD_CODING_SESSION ON CD_CODING_SESSION.Organizer_Id = CD_ORGANIZER.Organizer_Id
JOIN CD_LOCATION ON CD_LOCATION.loc_id = CD_CODING_SESSION.loc_id;

-- 3.
SELECT Organizer_Name FROM CD_ORGANIZER
UNION
SELECT Facilitator_Name FROM CD_FACILITATOR;

-- 4.
SELECT Facilitator_Name, Facilitator_email
FROM CD_FACILITATOR
WHERE Facilitator_Name NOT IN (
  SELECT Organizer_Name FROM CD_ORGANIZER);

-- 5.
SELECT DISTINCT Coder_Name, Badge_Earned, Spec_Name
FROM CD_ATTENDEE
JOIN CD_ATTENDS ON CD_ATTENDS.Coder_Id = CD_ATTENDEE.Coder_Id
JOIN CD_SESSION_RUNS ON CD_SESSION_RUNS.loc_id = CD_ATTENDS.loc_id
JOIN CD_SPECIALITY ON CD_SPECIALITY.Spec_code = CD_SESSION_RUNS.Spec_code
WHERE Badge_Earned IS NOT NULL;

-- 6.
