-- AGGREGATION
SELECT * FROM rtable;
SELECT * FROM Table_Booking;

SELECT COUNT(STATUS) AS Walk_ins
FROM Table_Booking
WHERE BOOKING_NAME IS NULL
AND
BOOKING_CONTACT IS NULL;

SELECT COUNT(*)
FROM TABLE_BOOKING
WHERE BOOKING_NAME = 'Quaverly'
AND
BOOK_DATE <= ADD_MONTHS(SYSDATE, -6);

SELECT BOOKING_NAME
FROM TABLE_BOOKING
GROUP BY BOOKING_NAME
HAVING COUNT(*) > 2;

-- SETS
SELECT * FROM Menu_Type;
SELECT * FROM menu;

SELECT DISH FROM menu
WHERE MENU_TIME = 'EBIRD'
UNION
SELECT DISH FROM menu
WHERE MENU_TIME = 'DNNER';

SELECT DISH FROM menu
WHERE MENU_TIME = 'EBIRD'
INTERSECT
SELECT DISH FROM menu
WHERE MENU_TIME = 'DNNER';

SELECT DISH FROM menu
WHERE MENU_TIME = 'DNNER'
MINUS
SELECT DISH FROM menu
WHERE MENU_TIME = 'EBIRD';

-- JOINS
SELECT TABLENO, TLOCATION, CAPACITY
FROM rTable
WHERE TABLENO NOT IN (
  SELECT TABLENO
  FROM Table_Booking
);
