CREATE OR REPLACE VIEW ESSENTIAL AS (
  SELECT MEMBER.MNAME, ITEMFORLOAN.BRANDNAME,
  LOAN.RETURNDATE, EQUIPMENTTYPE.EQCOMPANY,
  LOAN.LOANDATE, EQUIPMENTTYPE.COSTPERNIGHT
  FROM MEMBER
  JOIN LOAN ON LOAN.MEMBERID = MEMBER.MEMBERID
  JOIN ITEMFORLOAN ON ITEMFORLOAN.SERIALNO = LOAN.SERIALNO
  JOIN EQUIPMENTTYPE ON EQUIPMENTTYPE.BRANDNAME = ITEMFORLOAN.BRANDNAME
);

-- 1.
SELECT MNAME, BRANDNAME, COUNT(*)
FROM ESSENTIAL
GROUP BY MNAME, BRANDNAME
HAVING COUNT(*) > 1;

-- 2.
SELECT BRANDNAME FROM ITEMFORLOAN
WHERE SERIALNO NOT IN (
    SELECT SERIALNO FROM LOAN
);

-- 3.
SELECT MNAME FROM ESSENTIAL
WHERE BRANDNAME LIKE '%iPad%'
MINUS
SELECT MNAME FROM ESSENTIAL
WHERE BRANDNAME LIKE '%Watch%';

-- 4.
SELECT MNAME FROM ESSENTIAL
WHERE NOT EXISTS (
  SELECT BRANDNAME
  FROM ESSENTIAL
  WHERE NOT EXISTS (
    SELECT EQCOMPANY
    FROM ESSENTIAL
    WHERE EQCOMPANY = 'Dell'
  )
);

-- 5.
SELECT MNAME, ROUND(SYSDATE - LOANDATE) * COSTPERNIGHT AS Penalty
FROM ESSENTIAL
WHERE RETURNDATE IS NULL;
